# Generated by Django 5.0.4 on 2024-04-19 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "favourite_projects",
                    models.ManyToManyField(related_name="users", to="app_api.project"),
                ),
                (
                    "friends",
                    models.ManyToManyField(
                        related_name="friends", to="app_api.customer"
                    ),
                ),
                (
                    "projects",
                    models.ManyToManyField(
                        related_name="members", to="app_api.project"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app_api.customer"
            ),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
