# Generated by Django 5.0.4 on 2024-04-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_api", "0002_customer_alter_project_owner_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="friends",
            field=models.ManyToManyField(to="app_api.customer"),
        ),
    ]
