# Generated by Django 5.0.4 on 2024-04-19 21:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_api", "0003_alter_customer_friends"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="friends",
        ),
    ]
