# Generated by Django 5.0.4 on 2024-04-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_api", "0004_remove_customer_friends"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="profile_pic",
            field=models.ImageField(blank=True, upload_to="profile_pics"),
        ),
    ]
