# Generated by Django 5.0.4 on 2024-04-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_api", "0006_alter_customer_favourite_projects_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
