# Generated by Django 5.0.4 on 2024-04-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_api", "0007_customer_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="files"),
        ),
        migrations.AddField(
            model_name="file",
            name="file_extension",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
