# Generated by Django 5.0.4 on 2024-04-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_api", "0008_file_file_file_file_extension"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="files/<django.db.models.fields.related.ForeignKey>",
            ),
        ),
    ]
